spring:
  application:
     name: auth-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: auth

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5   # DO NOT DO THIS IN PRODUCTION

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port

jwt:
  secretKey: RHNuM2dNWWF6aDVhNkM0M2E1eG84ejcz